"""Export deterministic third-party inputs for consultation dependency locks."""

from __future__ import annotations

import argparse
import platform
import re
import struct
import sys
import tomllib
from pathlib import Path
from typing import Any, Literal, Sequence


LockProfile = Literal["core", "ml"]

SUPPORTED_PYTHONS = ("3.12", "3.13")
SUPPORTED_PROFILES = ("core", "ml")
TARGET_VERSIONS = {"3.12": (3, 12), "3.13": (3, 13)}
MINIMUM_PATCHES = {"3.12": 10, "3.13": 0}
TARGET_BITS = 64
BOOTSTRAP_REQUIREMENTS = (
    "pip==26.0.1",
    "setuptools==83.0.0",
    "wheel==0.47.0",
)
BASE_EXTRAS = (
    "mcp",
    "pdf",
    "office",
    "watch",
    "consultation-core",
    "consultation-test",
)
LEIDEN_EXTRA = "leiden"
ML_EXTRA = "consultation-ml"
TORCH_REQUIREMENTS = {
    "3.12": (
        "torch @ https://download-r2.pytorch.org/whl/cpu/"
        "torch-2.13.0%2Bcpu-cp312-cp312-win_amd64.whl"
        "#sha256=a8b450c1e58e5800e5b4691dac412f8d2d65a1dc3298166f91596603a3531e6f"
    ),
    "3.13": (
        "torch @ https://download-r2.pytorch.org/whl/cpu/"
        "torch-2.13.0%2Bcpu-cp313-cp313-win_amd64.whl"
        "#sha256=a17ff48608634db245e17e8bb00a9558554a49aeb1e4f5fe6cd039af2a10515b"
    ),
}
PROJECT_DISTRIBUTIONS = frozenset({"graphifyy", "consultation-kb"})
_DISTRIBUTION_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*")


def _load_pyproject(path: Path) -> dict[str, Any]:
    return tomllib.loads(path.read_text(encoding="utf-8"))


def _normalized_distribution_name(requirement: str) -> str:
    match = _DISTRIBUTION_NAME.match(requirement)
    if match is None:
        raise ValueError(f"invalid third-party requirement: {requirement!r}")
    return re.sub(r"[-_.]+", "-", match.group(0)).casefold()


def _validate_requirement(
    requirement: str,
    *,
    allowed_direct_requirement: str | None = None,
) -> None:
    if requirement.startswith("-"):
        raise ValueError(f"requirement options are forbidden: {requirement!r}")
    if _normalized_distribution_name(requirement) in PROJECT_DISTRIBUTIONS:
        raise ValueError(f"project distribution is forbidden: {requirement!r}")
    if " @ " in requirement and requirement != allowed_direct_requirement:
        raise ValueError(f"unapproved direct requirement: {requirement!r}")


def selected_extras(target_python: str, profile: LockProfile) -> tuple[str, ...]:
    """Return the exact extras admitted to one lock target."""
    extras = list(BASE_EXTRAS)
    if target_python == "3.12":
        extras.append(LEIDEN_EXTRA)
    if profile == "ml":
        extras.append(ML_EXTRA)
    return tuple(extras)


def exported_requirements(
    pyproject: dict[str, Any],
    *,
    target_python: str = "3.12",
    profile: LockProfile = "core",
) -> list[str]:
    """Return sorted third-party requirements for one consultation lock."""
    if target_python not in SUPPORTED_PYTHONS:
        raise ValueError(f"unsupported target Python: {target_python!r}")
    if profile not in SUPPORTED_PROFILES:
        raise ValueError(f"unsupported lock profile: {profile!r}")

    project = pyproject["project"]
    optional = project["optional-dependencies"]
    extras = selected_extras(target_python, profile)
    requirements = [*BOOTSTRAP_REQUIREMENTS, *project["dependencies"]]
    for extra in extras:
        requirements.extend(optional[extra])

    direct_requirement = TORCH_REQUIREMENTS[target_python] if profile == "ml" else None
    if direct_requirement is not None:
        requirements.append(direct_requirement)
    for requirement in requirements:
        _validate_requirement(
            requirement,
            allowed_direct_requirement=direct_requirement,
        )
    return sorted(set(requirements), key=lambda value: (value.casefold(), value))


def render_input(
    requirements: Sequence[str],
    *,
    target_python: str = "3.12",
    profile: LockProfile = "core",
) -> str:
    """Render a stable pip-tools input with no index or project directives."""
    extras = ", ".join(selected_extras(target_python, profile))
    header = (
        "# Generated by scripts/export_consultation_requirements.py.\n"
        f"# Target: Windows CPython {target_python} x64 ({profile}).\n"
        f"# Sources: bootstrap tools, project.dependencies, and extras {extras}.\n"
        "# Direct URLs, when present, are immutable official artifacts with SHA-256.\n"
        "# Do not edit by hand.\n"
        "\n"
    )
    return header + "\n".join(requirements) + "\n"


def _default_output(repo_root: Path, target_python: str, profile: LockProfile) -> Path:
    profile_part = "-ml" if profile == "ml" else ""
    compact_python = target_python.replace(".", "")
    return (
        repo_root
        / "requirements"
        / (f"consultation{profile_part}-win-py{compact_python}.in")
    )


def _parser() -> argparse.ArgumentParser:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--python", required=True, choices=SUPPORTED_PYTHONS)
    parser.add_argument("--profile", choices=SUPPORTED_PROFILES, default="core")
    parser.add_argument(
        "--pyproject",
        type=Path,
        default=repo_root / "pyproject.toml",
    )
    parser.add_argument("--output", type=Path)
    return parser


def _runtime_error(target_python: str) -> str:
    patch = MINIMUM_PATCHES[target_python]
    return (
        "requirements export requires Windows CPython "
        f"{target_python}.{patch} or later in the {target_python} series, 64-bit"
    )


def _runtime_matches_lock_target(target_python: str) -> bool:
    return (
        sys.platform == "win32"
        and platform.python_implementation() == "CPython"
        and sys.version_info[:2] == TARGET_VERSIONS[target_python]
        and sys.version_info[2] >= MINIMUM_PATCHES[target_python]
        and struct.calcsize("P") * 8 == TARGET_BITS
    )


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    target_python: str = args.python
    profile: LockProfile = args.profile
    if not _runtime_matches_lock_target(target_python):
        print(_runtime_error(target_python), file=sys.stderr)
        return 2

    requirements = exported_requirements(
        _load_pyproject(args.pyproject),
        target_python=target_python,
        profile=profile,
    )
    repo_root = Path(__file__).resolve().parents[1]
    output = args.output or _default_output(repo_root, target_python, profile)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_input(
            requirements,
            target_python=target_python,
            profile=profile,
        ),
        encoding="utf-8",
        newline="\n",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
